// Pre-seeded fallback data for instant offline / cold-start rendering
export const FALLBACK_CATEGORIES = [
  {
    "id": 2,
    "name": "Sweets",
    "slug": "sweets",
    "description": "Authentic sweets for every occasion",
    "image": null,
    "is_active": 1
  },
  {
    "id": 3,
    "name": "Perfumes",
    "slug": "perfumes",
    "description": null,
    "image": null,
    "is_active": 1
  },
  {
    "id": 4,
    "name": "Puja Essentials",
    "slug": "puja-essentials",
    "description": null,
    "image": null,
    "is_active": 1
  },
  {
    "id": 6,
    "name": "Gathiya",
    "slug": "gathiya",
    "description": "Authentic traditional Gujarati Gathiya, crafted using generational recipes and pure ingredients.",
    "image": "assets/placeholder-luxury.jpg",
    "is_active": 1
  },
  {
    "id": 7,
    "name": "Sev",
    "slug": "sev",
    "description": "Crispy, crunchy traditional Sev vermicelli, seasoned with hand-picked master masalas.",
    "image": "assets/placeholder-luxury.jpg",
    "is_active": 1
  },
  {
    "id": 8,
    "name": "Bhujia",
    "slug": "bhujia",
    "description": "The ultimate bold and fiery Bhujia, prepared with clean gram flour and traditional spices.",
    "image": "assets/placeholder-luxury.jpg",
    "is_active": 1
  },
  {
    "id": 9,
    "name": "Puri & Papadi",
    "slug": "puri-papadi",
    "description": "Crispy hand-crafted Puris and paper-thin flaky Papadi wafers, perfectly spiced for high tea.",
    "image": "assets/placeholder-luxury.jpg",
    "is_active": 1
  },
  {
    "id": 10,
    "name": "Mixture & Chevdo",
    "slug": "mixture-chevdo",
    "description": "Exquisite blended savory mixtures, dry Bhakharvadi, stuffed Kachori, and sweet-tangy Makai Chevdo.",
    "image": "assets/placeholder-luxury.jpg",
    "is_active": 1
  },
  {
    "id": 11,
    "name": "Chana & Peanuts",
    "slug": "chana-peanuts",
    "description": "Spiced roasted Chana dal, protein-rich Moong dal, and crispy peanuts coated in standard masalas.",
    "image": "assets/placeholder-luxury.jpg",
    "is_active": 1
  }
];

export const FALLBACK_PRODUCTS = [
  {
    "id": 1,
    "category_id": 10,
    "name": "Bhakharvadi",
    "name_gu": "પ્રીમિયમ ભાવનગરી ભાખરવડી | કરકરો ગુજરાતી નાસ્તો ૨૫૦ ગ્રામ",
    "slug": "bhakharvadi",
    "description": "Indulge in the authentic taste of Gujarat with our Premium Bhavnagri Bhakharvadi. These perfectly spiced, crispy spiral rolls are handcrafted using traditional recipes passed down through generations. Made with the finest besan (gram flour), aromatic spices, and a secret blend of sesame and dry fruits, each bite delivers an irresistible crunch and a burst of tangy-spicy flavour. Ideal for tea-time snacking, festive celebrations, or gifting. No artificial preservatives. Vacuum-sealed freshness guaranteed. Net Weight: 250g.",
    "description_gu": "પેઢીઓથી ચાલી આવતી પરંપરાગત વાનગીઓનો ઉપયોગ કરીને તૈયાર કરાયેલી આ ભાખરવડી મસાલેદાર અને ક્રિસ્પી છે. ઉત્તમ ચણાનો લોટ, સુગંધિત મસાલા, તલ અને સૂકા મેવાના મિશ્રણથી બનેલો આ નાસ્તો ચાના સમય માટે ઉત્તમ છે. કોઈ પણ કૃત્રિમ પ્રિઝર્વેટિવ્સ વગર વેક્યૂમ-સીલ્ડ પેકિંગમાં ઉપલબ્ધ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "bhakharvadi",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 2,
    "category_id": 9,
    "name": "Chakri",
    "name_gu": "પ્રીમિયમ ભાવનગરી ચકરી | ક્રિસ્પી ચોખાના લોટની ચકરી ૨૫૦ ગ્રામ",
    "slug": "chakri",
    "description": "Savour the classic taste of Gujarat with our Premium Bhavnagri Chakri. These golden, crispy spiral discs are made from a fine blend of rice flour and aromatic spices, expertly shaped and deep-fried to perfection. Each Chakri offers a satisfying crunch with a delicate balance of salt and spice. A beloved Gujarati snack enjoyed across generations â€“ perfect for evening chai, festive platters, and family gatherings. No artificial colours or flavours. Freshly packed for maximum crunch. Net Weight: 250g.",
    "description_gu": "ચોખાના લોટ અને સુગંધિત મસાલાના ઉત્તમ મિશ્રણમાંથી બનેલી આ ગોલ્ડન અને ક્રિસ્પી ચકરી સ્વાદિષ્ટ અને પરંપરાગત છે. સાંજની ચા, તહેવારો અને કૌટુંબિક મેળાવડા માટે શ્રેષ્ઠ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1xjf-rzKlQgHlD_Qfo9UkBqlJ_X7TLC_r",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "chakri",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 3,
    "category_id": 11,
    "name": "Chana Bhajiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી ચણા ભજીયા | ચણા દાળના કરકરા ભજીયા ૨૫૦ ગ્રામ",
    "slug": "chana-bhajiya",
    "description": "Experience the bold, spicy crunch of our Premium Bhavnagri Chana Bhajiya. Made from select whole chana dal coated in a seasoned gram flour batter and fried to a golden crisp, these savoury fritters are bursting with authentic Gujarati flavour. Every piece is perfectly seasoned with a blend of red chilli, turmeric, and cumin for a taste that keeps you reaching for more. Ideal as a standalone snack, chai companion, or party appetiser. No MSG. No artificial preservatives. Net Weight: 250g.",
    "description_gu": "ચણાની દાળ અને મસાલેદાર ચણાના લોટના ખીરામાંથી બનેલો આ કરકરો અને સ્વાદિષ્ટ નાસ્તો અસલી ગુજરાતી સ્વાદ આપે છે. લાલ મરચું, હળદર અને જીરાના પરફેક્ટ મિશ્રણ સાથે મસાલેદાર સ્વાદ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1td1u4FG4-WQxvOmhDwidxiR_JZTRCPKm",
    "brand": "Bhavnagri Foods",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "chana",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 4,
    "category_id": 11,
    "name": "Cheese Peanuts",
    "name_gu": "પ્રીમિયમ ભાવનગરી ચીઝ સીંગ | ચીઝી કોટેડ શેકેલી સીંગ ૨૫૦ ગ્રામ",
    "slug": "cheese-peanuts",
    "description": "Treat yourself to the irresistible fusion of crunchy roasted peanuts and rich, tangy cheese flavour with our Premium Bhavnagri Cheese Peanuts. Each peanut is carefully roasted and generously coated with a premium cheese seasoning that delivers a perfect balance of savoury and creamy notes. A modern twist on the classic Indian peanut snack â€“ perfect for movie nights, road trips, parties, or anytime snacking. Protein-rich and utterly addictive. No trans fats. No artificial preservatives. Net Weight: 250g.",
    "description_gu": "શેકેલી સીંગ and સમૃદ્ધ ચીઝ ફ્લેવરનું અદભુત મિશ્રણ. પિઝા નાઈટ અને પ્રવાસ માટે શ્રેષ્ઠ. પ્રોટીનથી ભરપૂર અને અત્યંત સ્વાદિષ્ટ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1YfJz97a4v3rzYbN1LgAVloUPjlGLNtLd",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "cheese",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 5,
    "category_id": 10,
    "name": "Dry Kachori",
    "name_gu": "પ્રીમિયમ ભાવનગરી ડ્રાય કચોરી | કરકરી મીની ડ્રાય કચોરી ૨૫૦ ગ્રામ",
    "slug": "dry-kachori",
    "description": "Discover the authentic flavour of Rajasthani-Gujarati cuisine with our Premium Bhavnagri Dry Kachori. These perfectly round, crispy mini kachoris are stuffed with a flavourful blend of moong dal, aromatic spices, and a hint of asafoetida, then deep-fried to golden perfection. Each bite reveals a delightful crunch on the outside and a rich, spiced filling inside. A timeless Indian snack perfect for tea time, travel, or festive occasions. No artificial colours. Sealed for freshness. Net Weight: 250g.",
    "description_gu": "મગની દાળ, સુગંધિત મસાલા અને હિંગના સ્વાદિષ્ટ મિશ્રણથી ભરેલી આ સોનેરી અને ક્રિસ્પી મિની કચોરી ચાના સમય કે મુસાફરી માટે ઉત્તમ છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1TleB2POv1P3w1No6JJwVjrs1mlsiB8N4",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "kachori",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 6,
    "category_id": 11,
    "name": "Fried Moong",
    "name_gu": "પ્રીમિયમ ભાવનગરી ફ્રાઈડ મગ | નમકીન મગની દાળ ૨૫૦ ગ્રામ",
    "slug": "fried-moong",
    "description": "Enjoy the simple yet addictive crunch of our Premium Bhavnagri Fried Moong. Whole moong dal is carefully selected, soaked, and deep-fried to achieve the perfect golden crunch, then lightly seasoned with rock salt and a touch of turmeric. This protein-packed, guilt-free snack is a Gujarati household staple â€“ perfect for munching on the go, adding crunch to your chaats, or pairing with your evening tea. Naturally gluten-free. No artificial additives. Net Weight: 250g.",
    "description_gu": "સોનેરી રંગે તળેલી અને સિંધાલૂણ મીઠું તેમજ હળદરથી સજાવેલી પ્રોટીનયુક્ત મગની દાળ. ચા સાથે ખાવા માટે એક ઉત્તમ અને પૌષ્ટિક નાસ્તો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1T_BOviHVoUYvFFAVXRiH5mI-p23UkUyX",
    "brand": "Bhavnagri Foods",
    "spiciness": 0,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "moong",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 7,
    "category_id": 11,
    "name": "Garlic Chana Bhajiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી લસણીયા ચણા ભજીયા | લસણ મસાલા ભજીયા ૨૫૦ ગ્રામ",
    "slug": "garlic-chana-bhajiya",
    "description": "Elevate your snack game with our Premium Bhavnagri Garlic Chana Bhajiya â€“ a bold, flavourful twist on the classic Gujarati bhajiya. Whole chana dal is infused with freshly crushed garlic, coated in a seasoned gram flour batter, and fried to a perfect golden crunch. The robust garlic aroma combined with the heat of red chilli and the earthiness of cumin creates an unforgettable taste experience. Perfect for garlic lovers who crave bold flavours with their chai. No MSG. No artificial flavours. Net Weight: 250g.",
    "description_gu": "ચણાની દાળ, તાજું લસણ અને મસાલેદાર ચણાના લોટના ખીરામાંથી બનેલો આ લસણીયો નાસ્તો લસણપ્રેમીઓ માટે એક અદભુત અનુભવ છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1td1u4FG4-WQxvOmhDwidxiR_JZTRCPKm",
    "brand": "Bhavnagri Foods",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "garlic",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 8,
    "category_id": 11,
    "name": "Hing Jeera Chana",
    "name_gu": "પ્રીમિયમ ભાવનગરી હિંગ જીરા ચણા | હિંગ અને જીરાના શેકેલા ચણા ૨૫૦ ગ્રામ",
    "slug": "hing-jeera-chana",
    "description": "Relish the aromatic duo of hing (asafoetida) and jeera (cumin) with our Premium Bhavnagri Hing Jeera Chana. Select whole roasted chana is tossed with pure hing, roasted cumin powder, black salt, and a hint of amchur (dry mango powder) for a flavour profile that is tangy, earthy, and deeply satisfying. This traditional Indian snack is rich in protein and fibre â€“ a wholesome alternative to fried snacks. Perfect for health-conscious snackers and flavour enthusiasts alike. No artificial colours or preservatives. Net Weight: 250g.",
    "description_gu": "હિંગ, શેકેલા જીરાનો પાવડર, સંચળ અને આમચૂરના મિશ્રણ સાથે તૈયાર કરેલા ચણા. સ્વાસ્થ્યપ્રદ અને સ્વાદિષ્ટ પ્રોટીનયુક્ત નાસ્તો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1B_tKfcZdWlDCZ_dM_j-QcXXM8lyqprVD",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "hing",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 9,
    "category_id": 6,
    "name": "Masala Gathiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી મસાલા ગાંઠિયા | સ્વાદિષ્ટ ચણાના લોટના ગાંઠિયા ૨૫૦ ગ્રામ",
    "slug": "masala-gathiya",
    "description": "Experience the irresistible garlic punch of our Premium Bhavnagri Lasaniya Gathiya. These thick, crunchy gram flour noodles are kneaded with fresh garlic paste and a robust spice blend, then pressed through traditional moulds and deep-fried to golden perfection. The bold lasaniya (garlic) flavour sets these apart from regular gathiya â€“ every strand is packed with aromatic garlic goodness. A must-have for garlic lovers and a staple in every Gujarati household. No artificial flavours. Freshly made and sealed. Net Weight: 250g.",
    "description_gu": "તાજા મસાલાની પેસ્ટ અને મસાલેદાર ચણાના લોટના મિશ્રણમાંથી બનેલા આ ગરમાગરમ સોનેરી ગાંઠિયા નાસ્તાના પ્રેમીઓ માટે શ્રેષ્ઠ પસંદગી છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1wwHh0K3kRuLpLUYNJbU80Ktq_s6zNY5U",
    "brand": "Bhavnagri Foods",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "masala",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 10,
    "category_id": 10,
    "name": "Makai Chevdo",
    "name_gu": "પ્રીમિયમ ભાવનગરી મકાઈ ચેવડો | ચટપટો મકાઈનો ચેવડો ૨૫૦ ગ્રામ",
    "slug": "makai-chevdo",
    "description": "Delight in the sweet-savoury-spicy symphony of our Premium Bhavnagri Makai Chevdo. This signature Gujarati mix combines crispy corn flakes (makai) with roasted peanuts, crunchy sev, curry leaves, mustard seeds, and a perfectly balanced seasoning of sugar, salt, and chilli. Every handful is a burst of contrasting textures and flavours â€“ the hallmark of authentic Gujarati chevdo. A festive favourite and everyday indulgence. No artificial preservatives. Packed fresh in food-grade pouches. Net Weight: 250g.",
    "description_gu": "મકાઈના પૌઆ, શેકેલી સીંગ, તીખી સેવ, મીઠા લીમડા અને સરસવના પરફેક્ટ મિશ્રણ સાથે બનેલો ખાટો-મીઠો-તીખો ચેવડો જે દરેક ગુજરાતી ઘરની ઓળખ છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1-ZS_THocS6tg_C-pKsduvnmvnrCe-DZ-",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "makai",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 11,
    "category_id": 6,
    "name": "Bhavnagri Gathiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી ગાંઠિયા | મુલાયમ મોળા ગાંઠિયા ૨૫૦ ગ્રામ",
    "slug": "bhavnagri-gathiya",
    "description": "Melt into the buttery softness of our Premium Bhavnagri Makhaniya Gathiya. Unlike regular gathiya, these are crafted with a special dough enriched with extra oil and butter flavouring, giving them a distinctively smooth, melt-in-the-mouth texture. Lightly spiced with black pepper and ajwain (carom seeds), each strand offers a delicate crunch that dissolves into rich, buttery flavour. The softest gathiya in our range â€“ ideal for those who prefer mild, comforting snacks. No artificial colours. Freshly prepared. Net Weight: 250g.",
    "description_gu": "ખાસ લોટ અને માખણના સ્વાદ સાથે અત્યંત મુલાયમ અને મોઢામાં ઓગળી જાય તેવા ગાંઠિયા. મરી અને અજમાનો હળવો સ્વાદ આ નાષ્ટાને વધુ સ્વાદિષ્ટ બનાવે છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/17YcrtIoQSdbGsGHCkADCqb-9oR_g0MrN",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "bhavnagri",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 12,
    "category_id": 6,
    "name": "Mari Gathiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી મરી ગાંઠિયા | કાળા મરીના ગાંઠિયા ૨૫૦ ગ્રામ",
    "slug": "mari-gathiya",
    "description": "Ignite your taste buds with our Premium Bhavnagri Mari Gathiya. These thick, robust gram flour noodles are generously seasoned with freshly ground black pepper (mari), creating a bold, warming heat that lingers with every bite. The coarse texture and peppery kick make this the most flavourful gathiya in our collection. Crafted using time-honoured Bhavnagri techniques with pure ingredients. A favourite among spice lovers and a perfect companion to hot masala chai. No artificial spices. Freshly sealed. Net Weight: 250g.",
    "description_gu": "તીખા અને ગરમાગરમ કાળા મરીના પાવડર સાથે બનેલા ચણાના લોટના ગાંઠિયા. તીખાશના શોખીનો માટે ચા સાથે એક અદભુત જોડી. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/19vQ8EUEicmNF9JpNDH8mjgynNhtzv1-7",
    "brand": "Bhavnagri Foods",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "mari",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 13,
    "category_id": 6,
    "name": "Nylon Gathiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી નાયલોન ગાંઠિયા | રેશમી બારીક ગાંઠિયા ૨૫૦ ગ્રામ",
    "slug": "nylon-gathiya",
    "description": "Discover the legendary smoothness of our Premium Bhavnagri Nylon Gathiya â€“ the finest and thinnest gathiya you will ever taste. These ultra-fine gram flour strands are as delicate as silk threads, pressed through the finest sev moulds and fried to an airy, feather-light crispiness. Named for their nylon-like fineness, they dissolve on your tongue with a subtle spice and a satisfying crunch. Perfect as a topping for chaats, mixed with chevdo, or enjoyed on their own. A Bhavnagri speciality. No preservatives. Net Weight: 250g.",
    "description_gu": "ભાવનગરની એક વિશેષતા - અત્યંત પાતળી અને રેશમ જેવી મુલાયમ સેવ જે મોઢામાં મુકતા જ ઓગળી જાય છે. ભેળ કે ચાટ પર નાખવા માટે કે એકલા ખાવા માટે પણ શ્રેષ્ઠ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1tblzxpC_GtliNgyKWkC7Za5axu0hK7qw",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "nylon",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 14,
    "category_id": 10,
    "name": "Papad Chevdo",
    "name_gu": "પ્રીમિયમ ભાવનગરી પાપડ ચેવડો | ક્રિસ્પી પાપડનો ચેવડો ૨૫૦ ગ્રામ",
    "slug": "papad-chevdo",
    "description": "Experience the unique crunch of our Premium Bhavnagri Papad Chevdo â€“ a distinctive Gujarati snack mix built around crispy, crumbled papad pieces. Bite-sized papad flakes are combined with roasted peanuts, sesame seeds, curry leaves, and a sweet-spicy-tangy seasoning that captures the essence of Gujarati flavour. The irregular shapes and textures create a snacking experience unlike any other chevdo. A rare and authentic recipe from the kitchens of Bhavnagar. No artificial colours or preservatives. Net Weight: 250g.",
    "description_gu": "ક્રિસ્પી પાપડના ટુકડા, શેકેલી સીંગ અને તલના મિશ્રણ સાથે બનેલો ભાવનગરની પરંપરાગત વાનગીનો સ્વાદિષ્ટ ચેવડો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1J1g5PZkSqIzf7EUL0-1w0-Q-eupjXO3E",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "papad",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 15,
    "category_id": 9,
    "name": "Pizza Puri",
    "name_gu": "પ્રીમિયમ ભાવનગરી પિઝા પુરી | ઇટાલિયન-ઇન્ડિયન ફ્યુઝન પુરી ૨૫૦ ગ્રામ",
    "slug": "pizza-puri",
    "description": "Embark on a flavour adventure with our Premium Bhavnagri Pizza Puri â€“ where Italian pizza seasoning meets the crispy Indian puri. These thin, crunchy mini puris are generously dusted with a tangy-spicy pizza-inspired seasoning blend featuring oregano, tomato powder, cheese flavour, and a hint of chilli. A modern fusion snack that appeals to all ages â€“ kids love the cheesy-tangy taste, adults appreciate the satisfying crunch. Perfect for parties, lunchboxes, and on-the-go munching. No trans fats. Vegetarian. Net Weight: 250g.",
    "description_gu": "ઇટાલિયન પિઝાના મસાલા અને ભારતની ક્રિસ્પી પુરીનું એક અનોખું ફ્યુઝન. ઓરેગાનો, ટમેટા અને ચીઝના ફ્લેવર સાથે બાળકો અને વડીલો માટે મજેદાર નાસ્તો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1uJ45zcuTcXA4LxzUhERXO4xkeRoNBbA4",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "pizza",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 16,
    "category_id": 11,
    "name": "Salted Peanuts",
    "name_gu": "પ્રીમિયમ ભાવનગરી ખારી સીંગ | ક્લાસિક શેકેલી નમકીન સીંગ ૨૫૦ ગ્રામ",
    "slug": "salted-peanuts",
    "description": "Keep it classic with our Premium Bhavnagri Salted Peanuts. Handpicked, premium-grade peanuts are slow-roasted to bring out their natural nutty richness, then perfectly seasoned with fine rock salt. Simple, satisfying, and packed with natural protein, healthy fats, and essential minerals. Whether you are snacking between meals, fuelling a workout, or adding crunch to your salads and chaats, these salted peanuts are the perfect wholesome choice. No added oil. No artificial flavours. Naturally gluten-free. Net Weight: 250g.",
    "description_gu": "ધીમી આંચે શેકેલી અને સિંધાલૂણ મીઠાથી સજાવેલી ક્લાસિક સીંગ. કુદરતી પ્રોટીન અને ફાઇબરથી ભરપૂર તંદુરસ્ત નાસ્તો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1YhVHFwgDmhKv6dq-apK3OmQqZb00ANU6",
    "brand": "Bhavnagri Foods",
    "spiciness": 0,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "salted",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 17,
    "category_id": 7,
    "name": "Nylon Sev",
    "name_gu": "પ્રીમિયમ ભાવનગરી નાયલોન સેવ | મસાલેદાર ઝીણી સેવ ૨૫૦ ગ્રામ",
    "slug": "nylon-sev",
    "description": "Savour the quintessential Gujarati snack with our Premium Bhavnagri Special Sev. These fine gram flour vermicelli strands are crafted from a premium besan dough seasoned with a proprietary spice blend, pressed through precision moulds, and fried to a uniform golden crispiness. Our 'Special' recipe includes a secret touch of ajwain and black salt that elevates this sev above the ordinary. Essential for topping chaats, garnishing dishes, or straight-from-the-pack snacking. A kitchen staple and a snack-time star. Net Weight: 250g.",
    "description_gu": "ચણાના લોટ અને અજમાના પરફેક્ટ મિશ્રણથી બનેલી સોનેરી અને મસાલેદાર સેવ. ચાટને ગાર્નિશ કરવા કે ચા સાથે સ્વાદ માણવા માટે શ્રેષ્ઠ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/14QGf0yk8NzBK0bPSgPD8U4Fvnh4Zy2IO",
    "brand": "Bhavnagri Foods",
    "spiciness": 0,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "nylon",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 18,
    "category_id": 11,
    "name": "Chatpata Peanuts",
    "name_gu": "પ્રીમિયમ ભાવનગરી ચટપટી સીંગ | ખાટી મીઠી મસાલા સીંગ ૨૫૦ ગ્રામ",
    "slug": "chatpata-peanuts",
    "description": "Get hooked on the playful sweet-and-sour dance of our Premium Bhavnagri Sweet & Chatpata Peanuts. Crunchy roasted peanuts are coated with a unique sweet-tangy-spicy masala blend featuring jaggery, amchur (dry mango), chaat masala, and a kick of red chilli. The result is an explosively flavourful snack that hits every taste note â€“ sweet, sour, spicy, and salty â€“ in perfect harmony. A crowd-pleaser at every gathering and impossible to stop at just one handful. Vegetarian. No artificial sweeteners. Net Weight: 250g.",
    "description_gu": "ગોળ, આમચૂર અને ચાટ મસાલાના કોટિંગ સાથે ખાટો-મીઠો-તીખો સ્વાદ ધરાવતી અદભુત સીંગ જે કોઈ પણ મેળાવડાની શાન બની જશે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1tqM-0ErIrcjMlZfjsv-tayAiHRdaIiMA",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "chatpata",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 19,
    "category_id": 6,
    "name": "Tikha Gathiya",
    "name_gu": "પ્રીમિયમ ભાવનગરી તીખા ગાંઠિયા | મસાલેદાર તીખા ગાંઠિયા ૨૫૦ ગ્રામ",
    "slug": "tikha-gathiya",
    "description": "Dare to take on the heat with our Premium Bhavnagri Tikha Gathiya â€“ the spiciest gathiya in our range. These thick, crunchy gram flour noodles are loaded with an extra-hot blend of red chilli, black pepper, and a proprietary 'tikha masala' that delivers an intense, lingering heat. Not for the faint-hearted â€“ this is gathiya for true spice warriors. The aggressive spice level is balanced by the nutty richness of premium besan, making every fiery bite deeply satisfying. Made with pure spices. Freshly sealed for potency. Net Weight: 250g.",
    "description_gu": "લાલ મરચું અને તીખા મસાલાથી ભરપૂર ચણાના લોટના તીખા ગાંઠિયા. તીખાશના ચાહકો માટે એક પડકારરૂપ અને સ્વાદિષ્ટ નાસ્તો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1Xso6RnfKDjm6jrv1hFGdi0g_4Pd2N7wC",
    "brand": "Bhavnagri Foods",
    "spiciness": 3,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "tikha",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 20,
    "category_id": 9,
    "name": "Til Papdi",
    "name_gu": "પ્રીમિયમ ભાવનગરી તલ પાપડી | તલની ક્રિસ્પી પટ્ટી ૨૫૦ ગ્રામ",
    "slug": "til-papdi",
    "description": "Celebrate the timeless flavours of Gujarat with our Premium Bhavnagri Til Papdi. These paper-thin, crispy wafers are crafted from a delicate dough of gram flour enriched with generous amounts of white sesame seeds (til) and a subtle spice blend. Each papdi shatters into a delightful crunch, releasing the warm, nutty aroma of toasted sesame. A traditional Gujarati delicacy often served during festivals, weddings, and special occasions. Rich in calcium and iron from sesame seeds. No artificial additives. Freshly made. Net Weight: 250g.",
    "description_gu": "સફેદ તલ અને ચણાના લોટમાંથી બનેલી એકદમ પાતળી અને કરકરી પાપડી જે કૌટુંબિક પ્રસંગો અને તહેવારો માટે અસલી સ્વાદ લાવે છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1Qt_0yqqWQaNGWevhCZOsA1HpbfZEAbbK",
    "brand": "Bhavnagri Foods",
    "spiciness": 0,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "til",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 21,
    "category_id": 9,
    "name": "Magic Puri",
    "name_gu": "પ્રીમિયમ ભાવનગરી મેજિક પુરી | મસાલેદાર ફ્લેકી પુરી ૨૫૦ ગ્રામ",
    "slug": "magic-puri",
    "description": "Delight in the spellbinding taste of our Premium Bhavnagri Magic Puri. These circular, flaky, and crispy golden crackers are seasoned with a secret spices blend of black pepper, carom seeds, and a hint of turmeric. Expertly kneaded and rolled to perfection, each puri delivers a satisfying crunch and a rich, buttery savoriness that melts in your mouth. Perfect for tea-time, family picnics, or festive platters. No artificial colors. Freshly packed. Net Weight: 250g.",
    "description_gu": "મરી, અજમો અને હળદરથી સજાવેલી સોનેરી અને ક્રિસ્પી પુરી જે મોંમાં મુકતા જ ઓગળી જાય છે. ચાના સમય કે પિકનિક માટે ઉત્તમ. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1OxnDabNO6L5XGh0pDP6hBPyj2WprCggX",
    "brand": "Bhavnagri Foods",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "magic",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 22,
    "category_id": 10,
    "name": "Mix Kathol",
    "name_gu": "પ્રીમિયમ ભાવનગરી મિક્સ કઠોળ | અંકુરિત મસાલેદાર કઠોળ ૨૫૦ ગ્રામ",
    "slug": "mix-kathol",
    "description": "Savor the wholesome crunch and authentic spices of our Premium Bhavnagri Mix Kathol. This traditional Gujarati namkeen is a vibrant mix of slow-roasted sprouted legumes (kathol) including green mung, moth beans, and black chick peas, tossed with golden sev, crispy peanuts, and infused with red chilli, dry mango powder, and aromatic hing. Packed with protein and dietary fibre, it is the perfect guilt-free snack for health-conscious snackers and spice lovers alike. Net Weight: 250g.",
    "description_gu": "અંકુરિત કઠોળ, મગ, મઠ અને ચણાને શેકીને તીખી સેવ, સીંગ અને હિંગના વઘાર સાથે તૈયાર કરેલો પૌષ્ટિક અને નમકીન નાસ્તો. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1nQaLTgT5VZ1Sq-7ATNmTrqcHZVTkq4up",
    "brand": "Bhavnagri Foods",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "kathol",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 23,
    "category_id": 9,
    "name": "Nylon Papadi",
    "name_gu": "પ્રીમિયમ ભાવનગરી નાયલોન પાપડી | ક્રિસ્પી પાતળી પાપડી ૨૫૦ ગ્રામ",
    "slug": "nylon-papadi",
    "description": "Experience the delicate, paper-thin crunch of our Premium Bhavnagri Nylon Papadi. These long, ultra-fine crispy ribbons are crafted from a seasoned gram flour (besan) dough enriched with carom seeds (ajwain) and a touch of asafoetida. Deep-fried to a light, golden airiness, each papadi melts on your tongue with a mild, comforting spice. A classic Gujarati snack typically served during Sunday breakfasts with fresh jalebis and spicy papaya sambharo. No preservatives. Net Weight: 250g.",
    "description_gu": "ચણાના લોટ, અજમો અને હિંગના સ્વાદથી ભરપૂર સોનેરી રંગે તળેલી પાતળી રીબન જેવી પાપડી જે રવિવારના સવારના નાસ્તા માટે જલેબી સાથે ઉત્તમ જોડી બનાવે છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1MxcY3M-cFOsggnqZ_TADQdJPIq4-WY5u",
    "brand": "Bhavnagri Foods",
    "spiciness": 0,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "nylon",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 24,
    "category_id": 10,
    "name": "Jhal Muri",
    "name_gu": "પ્રીમિયમ ભાવનગરી ઝાલ મુરી | ચટપટી તીખી મમરાની ભેળ ૨૫૦ ગ્રામ",
    "slug": "jhal-muri",
    "description": "Ignite your senses with the iconic street food flavor of our Premium Bhavnagri Jhal Muri. This classic Bengali-Gujarati fusion namkeen features light, airy puffed rice (muri) tossed with crunchy sev, roasted peanuts, dried coconut slices, and an explosive, tangy-spicy spice blend that mimics the authentic mustard oil and mango pickle infusion. Extremely light, fiery, and addictive - it is the ultimate companion for evening chats and rainy afternoons. Net Weight: 250g.",
    "description_gu": "પૂર્વ અને પશ્ચિમનો એક અનોખો સમન્વય - તીખી સેવ, શેકેલી સીંગ અને અસલી સરસવના તેલના ફ્લેવર સાથે બનેલી ઝાલ મુરી સાંજની વાતો માટે એક ઉત્તમ નાસ્તો છે. વજન: ૨૫૦ ગ્રામ.",
    "original_price": "249.00",
    "selling_price": "199.00",
    "image": "https://lh3.googleusercontent.com/d/1eWkfd1cLYWiBg64KABuuEf3RSQINzwOD",
    "brand": "Bhavnagri Foods",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "jhal",
    "is_featured": 0,
    "is_active": 1
  },
  {
    "id": 25,
    "category_id": 6,
    "name": "Fulwadi Gathiya",
    "name_gu": "પ્રીમિયમ ફૂલવડી ગાંઠિયા ૨૫૦ ગ્રામ",
    "slug": "fulwadi-gathiya",
    "description": "Crispy and spiced traditional Gathiya scrolls prepared using age-old kitchen recipes.",
    "description_gu": "પરંપરાગત રસોઈ પદ્ધતિ અને ઉત્તમ મસાલાઓથી બનેલા કરકરા અને સ્વાદિષ્ટ ફૂલવડી ગાંઠિયા.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "fulwadi",
    "is_featured": 1,
    "is_active": 1
  },
  {
    "id": 26,
    "category_id": 7,
    "name": "Tomato Sev",
    "name_gu": "પ્રીમિયમ ટમેટા સેવ ૨૫૦ ગ્રામ",
    "slug": "tomato-sev",
    "description": "Tangy and crunchy thin Sev seasoned with real dried tomato extracts and standard masalas.",
    "description_gu": "સાચા સૂકા ટમેટાના અર્ક અને પરંપરાગત મસાલાઓથી સજાવેલી ખાટી-મીઠી કરકરી સેવ.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "tomato",
    "is_featured": 1,
    "is_active": 1
  },
  {
    "id": 27,
    "category_id": 7,
    "name": "Lasan Sev",
    "name_gu": "પ્રીમિયમ લસણ સેવ ૨૫૦ ગ્રામ",
    "slug": "lasan-sev",
    "description": "Authentic garlic-infused thin Sev prepared with fresh lahsun paste for a powerful savory bite.",
    "description_gu": "તાજા લસણની પેસ્ટથી બનેલી અસલી મસાલેદાર સેવ, જે ચાના સમય માટે એક સારો નાસ્તો છે.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "lasan",
    "is_featured": 1,
    "is_active": 1
  },
  {
    "id": 28,
    "category_id": 7,
    "name": "Ratlami Sev",
    "name_gu": "પ્રીમિયમ રતલામી સેવ ૨૫૦ ગ્રામ",
    "slug": "ratlami-sev",
    "description": "Extra spicy Ratlami Sev prepared with ground black pepper, cloves, and premium spices.",
    "description_gu": "કાળા મરી, લવિંગ અને શાહી ગરમ મસાલાના મિશ્રણથી તૈયાર કરાયેલી અત્યંત તીખી રતલામી સેવ.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 3,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "ratlami",
    "is_featured": 1,
    "is_active": 1
  },
  {
    "id": 29,
    "category_id": 8,
    "name": "Garlic Bhujia",
    "name_gu": "પ્રીમિયમ લસણ ભુજીયા ૨૫૦ ગ્રામ",
    "slug": "garlic-bhujia",
    "description": "Authentic crispy Garlic Bhujia seasoned with hand-made masalas and spicy garlic paste.",
    "description_gu": "તાજા લસણ અને અસલી મસાલાઓ સાથે તૈયાર કરેલી લસણીયા ભુજીયા.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "garlic",
    "is_featured": 1,
    "is_active": 1
  },
  {
    "id": 30,
    "category_id": 8,
    "name": "Chana Bhujia",
    "name_gu": "પ્રીમિયમ ચણા ભુજીયા ૨૫૦ ગ્રામ",
    "slug": "chana-bhujia",
    "description": "Spicy Bhujia prepared from healthy chana dal flour and special spices.",
    "description_gu": "મગની દાળ અને ખાસ તેજ મસાલાઓથી તૈયાર કરેલી સ્વાદિષ્ટ ચણા ભુજીયા.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 2,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "chana",
    "is_featured": 1,
    "is_active": 1
  },
  {
    "id": 31,
    "category_id": 8,
    "name": "Aloo Bhujia",
    "name_gu": "પ્રીમિયમ આલૂ ભુજીયા ૨૫૦ ગ્રામ",
    "slug": "aloo-bhujia",
    "description": "Perfect mild crispiness, prepared from mashed potatoes and authentic spices.",
    "description_gu": "બટાકા અને હળવા ભારતીય મસાલાઓથી બનેલો દરેક ઉંમરના લોકોનો મનપસંદ કરકરો નાસ્તો.",
    "original_price": "150.00",
    "selling_price": "130.00",
    "image": "https://lh3.googleusercontent.com/d/1UX1vQMgwkEDk-6iIuadnlY8f1tLOV5_o",
    "brand": "Bhavnagris",
    "spiciness": 1,
    "rating": "4.8",
    "rating_count": 120,
    "tags": "aloo",
    "is_featured": 1,
    "is_active": 1
  }
];
