import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLangSubject = new BehaviorSubject<string>(localStorage.getItem('bhav_lang') || 'english');
  public currentLang$ = this.currentLangSubject.asObservable();

  private translations: { [lang: string]: { [key: string]: string } } = {
    english: {
      'catalog': 'Catalog',
      'heritage': 'Heritage',
      'home': 'Home',
      'my_orders': 'My Orders',
      'sign_out': 'Sign Out',
      'login': 'Login',
      'register': 'Register',
      'search': 'Search',
      'shop_now': 'Shop Now',
      'explore_heritage': 'Explore Heritage',
      'featured_delicacies': 'Featured Delicacies',
      'browse_categories': 'Browse Categories',
      'all_products': 'All Products',
      'snacks': 'Snacks',
      'sweets': 'Sweets',
      'spiciness': 'Spiciness',
      'price_low_high': 'Price: Low to High',
      'price_high_low': 'Price: High to Low',
      'latest_arrivals': 'Latest Arrivals',
      'add_to_basket': 'Add to Basket',
      'weight': 'Weight',
      'your_royal_basket': 'Your Royal Basket',
      'empty_cart': 'Your basket is empty',
      'order_summary': 'Order Summary',
      'subtotal': 'Subtotal',
      'delivery': 'Delivery',
      'total': 'Total',
      'proceed_checkout': 'Proceed to Checkout',
      'free': 'Free',
      'contact_royalty': 'Contact Royalty',
      'full_name': 'Full Name',
      'email_address': 'Email Address',
      'phone_number': 'Phone Number',
      'message': 'Message',
      'send_message': 'Send Message',
      'royal_guarantee': 'Our Guarantee of Royalty',
      'royal_guarantee_desc': 'Every packet of Bhavnagris is prepared following authentic methods, sourcing only choice local spices and fresh ingredients. We guarantee full refund or replacement if the taste does not feel royal.',
      'fast_delivery': 'Fast Pan-India Delivery',
      'secure_payments': 'Secure Payments',
      'concierge_support': '24/7 Concierge Support',
      'experience_premium': 'Experience Premium',
      'newsletter_desc': 'Sign up for early access to our luxury snack collections.',
      'subscribe': 'Subscribe',
      'logo_sub': 'A Royal Heritage of Gujarati Snacks. Authentic taste crafted with tradition.',
      'shop': 'Shop',
      'about': 'About',
      'our_story': 'Our Story',
      'contact': 'Contact',
      'social': 'Social',
      'inquiry_type': 'Inquiry Type',
      'general_inquiry': 'General Inquiry',
      'order_support': 'Order Support',
      'corporate_gifting': 'Corporate Gifting',
      'feedback': 'Feedback',
      'brand': 'Our Brand'
    },
    gujarati: {
      'catalog': 'મેનુ',
      'heritage': 'વારસો',
      'home': 'મુખ્ય પૃષ્ઠ',
      'my_orders': 'મારા ઓર્ડર',
      'sign_out': 'લૉગ આઉટ',
      'login': 'લૉગિન',
      'register': 'નોંધણી કરો',
      'search': 'શોધો',
      'shop_now': 'ખરીદી કરો',
      'explore_heritage': 'વારસો જાણો',
      'featured_delicacies': 'શાહી વાનગીઓ',
      'browse_categories': 'શ્રેણીઓ શોધો',
      'all_products': 'બધા ઉત્પાદનો',
      'snacks': 'નાસ્તા',
      'sweets': 'મીઠાઈઓ',
      'spiciness': 'તીખાશ',
      'price_low_high': 'કિંમત: ઓછી થી વધુ',
      'price_high_low': 'કિંમત: વધુ થી ઓછી',
      'latest_arrivals': 'નવા ઉત્પાદનો',
      'add_to_basket': 'કાર્ટમાં ઉમેરો',
      'weight': 'વજન',
      'your_royal_basket': 'તમારી શાહી ટોપલી',
      'empty_cart': 'તમારી ટોપલી ખાલી છે',
      'order_summary': 'ઓર્ડર સારાંશ',
      'subtotal': 'કુલ કિંમત',
      'delivery': 'મોકલવાનું ભાડું',
      'total': 'કુલ ચૂકવણી',
      'proceed_checkout': 'ચૂકવણી કરવા આગળ વધો',
      'free': 'મફત',
      'contact_royalty': 'અમારો સંપર્ક કરો',
      'full_name': 'આખું નામ',
      'email_address': 'ઈમેલ આઈડી',
      'phone_number': 'મોબાઈલ નંબર',
      'message': 'સંદેશ',
      'send_message': 'સંદેશ મોકલો',
      'royal_guarantee': 'શાહી સ્વાદની ખાતરી',
      'royal_guarantee_desc': 'ભાવનગરીસનું દરેક પેકેટ પરંપરાગત પદ્ધતિઓ દ્વારા, માત્ર ઉત્તમ સ્થાનિક મસાલા અને તાજી સામગ્રીનો ઉપયોગ કરીને તૈયાર કરવામાં આવે છે. જો સ્વાદ શાહી ન લાગે, તો અમે સંપૂર્ણ રિફંડ અથવા બદલીની ખાતરી આપીએ છીએ.',
      'fast_delivery': 'સમગ્ર ભારતમાં ઝડપી ડિલિવરી',
      'secure_payments': 'સુરક્ષિત ચૂકવણીઓ',
      'concierge_support': '૨૪/૭ ગ્રાહક સહાય',
      'experience_premium': 'પ્રીમિયમ સ્વાદનો અનુભવ કરો',
      'newsletter_desc': 'અમારા શાહી નાસ્તાના કલેક્શન માટે વહેલી તક મેળવવા સબ્સ્ક્રાઇબ કરો.',
      'subscribe': 'જોડાઓ',
      'logo_sub': 'ગુજરાતી નાસ્તાનો એક શાહી વારસો. પરંપરા સાથે બનાવેલો અસલી સ્વાદ.',
      'shop': 'ખરીદી',
      'about': 'વિશે',
      'our_story': 'અમારી વાર્તા',
      'contact': 'સંપર્ક',
      'social': 'સોશિયલ મીડિયા',
      'inquiry_type': 'સંપર્કનું કારણ',
      'general_inquiry': 'સામાન્ય પૂછપરછ',
      'order_support': 'ઓર્ડર સહાય',
      'corporate_gifting': 'ગિફ્ટિંગ સેવાઓ',
      'feedback': 'પ્રતિસાદ',
      'brand': 'ખાસ બ્રાન્ડ'
    },
    hindi: {
      'catalog': 'उत्पाद सूची',
      'heritage': 'धरोहर',
      'home': 'मुख्य पृष्ठ',
      'my_orders': 'मेरे ऑर्डर',
      'sign_out': 'लॉग आउट',
      'login': 'लॉगिन',
      'register': 'रजिस्टर करें',
      'search': 'खोजें',
      'shop_now': 'अभी खरीदें',
      'explore_heritage': 'धरोहर जानें',
      'featured_delicacies': 'विशेष व्यंजन',
      'browse_categories': 'श्रेणियाँ खोजें',
      'all_products': 'सभी उत्पाद',
      'snacks': 'नमकीन',
      'sweets': 'मिठाई',
      'spiciness': 'तीखापन',
      'price_low_high': 'कीमत: कम से अधिक',
      'price_high_low': 'कीमत: अधिक से कम',
      'latest_arrivals': 'नवीनतम उत्पाद',
      'add_to_basket': 'टोकरी में डालें',
      'weight': 'वजन',
      'your_royal_basket': 'आपकी शाही टोकरी',
      'empty_cart': 'आपकी टोकरी खाली है',
      'order_summary': 'ऑर्डर सारांश',
      'subtotal': 'कुल मूल्य',
      'delivery': 'डिलिवरी शुल्क',
      'total': 'कुल देय',
      'proceed_checkout': 'चेकआउट के लिए आगे बढ़ें',
      'free': 'मुफ़्त',
      'contact_royalty': 'शाही संपर्क',
      'full_name': 'पूरा नाम',
      'email_address': 'ईमेल पता',
      'phone_number': 'फ़ोन नंबर',
      'message': 'संदेश',
      'send_message': 'संदेश भेजें',
      'royal_guarantee': 'शाही स्वाद की गारंटी',
      'royal_guarantee_desc': 'भावनगरीस का हर पैकेट पारंपरिक विधियों से, केवल चुनिंदा स्थानीय मसालों और ताजी सामग्री से बनाया जाता है। यदि स्वाद शाही न लगे, तो हम पूर्ण धन वापसी या प्रतिस्थापन की गारंटी देते हैं।',
      'fast_delivery': 'पूरे भारत में तेज़ डिलीवरी',
      'secure_payments': 'सुरक्षित भुगतान',
      'concierge_support': '२४/७ ग्राहक सेवा',
      'experience_premium': 'प्रीमियम अनुभव का आनंद लें',
      'newsletter_desc': 'हमारे नए शाही स्नैक्स की जानकारी सबसे पहले पाने के लिए सब्सक्राइब करें।',
      'subscribe': 'जुड़ें',
      'logo_sub': 'गुजराती स्नैक्स की एक शाही विरासत। परंपरा के साथ तैयार असली स्वाद।',
      'shop': 'दुकान',
      'about': 'हमारे बारे में',
      'our_story': 'हमारी कहानी',
      'contact': 'संपर्क करें',
      'social': 'सोशल मीडिया',
      'inquiry_type': 'संपर्क का प्रकार',
      'general_inquiry': 'सामान्य पूछताछ',
      'order_support': 'ऑर्डर सहायता',
      'corporate_gifting': 'कॉर्पोरेट उपहार',
      'feedback': 'प्रतिक्रिया',
      'brand': 'खास ब्रांड'
    }
  };

  getCurrentLanguage(): string {
    return this.currentLangSubject.value;
  }

  setLanguage(lang: string) {
    localStorage.setItem('bhav_lang', lang);
    this.currentLangSubject.next(lang);
  }

  t(key: string): string {
    const lang = this.getCurrentLanguage();
    const dictionary = this.translations[lang] || this.translations['english'];
    return dictionary[key] || this.translations['english'][key] || key;
  }
}
